[package]
name = "image-black"
version = "0.1.0"
authors = ["elbaro <elbaro@github>"]

[dependencies]
rayon = "1.0.3"
image = "0.21.1"
walkdir = "2.2.7"
indicatif = "0.11.0"
regex = "1.1.6"
lazy_static = "1.3.0"
derivative = "1.0.2"
atomic-counter = "1.0.1"
colored= "1.7.0"
tempfile= "3.0.7"
